---
- name: Setup the server
  hosts: all
  become: true
  become_method: sudo 

  tasks: 
    - name: Install packages 
      apt:
          update_cache: yes
          name: "{{item }}"
          state: present 
      with_items:
          - python-pip
          - nginx

