---
- name: Setup the server
  hosts: all
  become: true
  become_method: sudo 
  gather_facts: false
  vars:
      work_dir: /home/ubuntu
      supervisor_dir: /etc/supervisor/conf.d
      app_name: the_simple_app

  pre_tasks:
      - name: Ensure that Python is installed
        raw: test -e /usr/bin/python || (apt -y update && apt -y install python-simplejson)
        register: output
        changed_when: output.stdout != ""
  roles: 
      - role: supervisor 

  tasks: 
    - name: Install packages 
      apt:
          update_cache: yes
          name: "{{item }}"
          state: present 
      with_items:
          - python-pip
          - nginx

    - name: Copy pip requirements file
      copy: 
        src: requirements.txt
        dest: "{{ work_dir }}/requirements.txt"

    - name: Install webapp requirements with pip
      pip: 
        requirements: "{{ work_dir }}/requirements.txt"

    - name: Copy nginx site configuration
      template:
          src: templates/nginx_wepapp.j2
          dest: /etc/nginx/sites-available/webapp
      tags: configs  

    - name: Enable webapp site
      file:
          src: /etc/nginx/sites-available/webapp
          dest: /etc/nginx/sites-enabled/webapp
          state: link
      notify: restart nginx
    
    - name: Disable default site config
      file: 
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Copy the python app
      copy: 
        src: simple_app.py
        dest: "{{ work_dir }}/simple_app.py"

    - name: Copy the supervisor job file
      template: 
        src: templates/supervisor_app.j2
        dest: "{{ supervisor_dir }}/supervisor_app.conf"
        owner: root
      notify: restart supervisor 

    - name: START the Job... Finally!!!
      supervisorctl: 
        name: "{{ app_name }}"
        state: present 

  handlers:
    - name: restart nginx
      service: 
        name: nginx
        state: restarted
    - name: restart supervisor
      service: 
        name: supervisor
        state: restarted



