---
- name: Install supervisor
  become: true
  apt: 
      name: supervisor
      state: present 
      update_cache: yes
  tags: 
    supervisor

- name: Start and enable supervisor service
  service: 
    name: supervisor
    state: running
    enabled: yes
  tags:
    supervisor
    
